name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: Build
        run: bash build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/jsonform-win-amd64.exe
            build/jsonform-win-arm64.exe
            build/jsonform-linux-amd64
            build/jsonform-linux-arm64
            build/jsonform-mac-amd64
            build/jsonform-mac-arm64
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
